In [4]:
import pandas as pd
data={
    "Name":["Alice","Bob","Claire","Lisa","Tom"],
    "Age":[25,28,30,26,14],
    "Department":["CSE","ECE","IT",'CSE',"ECE"],
    "Marks":[90,80,66,74,55]
    }
df=pd.DataFrame(data)

print(df)

     Name  Age Department  Marks
0   Alice   25        CSE     90
1     Bob   28        ECE     80
2  Claire   30         IT     66
3    Lisa   26        CSE     74
4     Tom   14        ECE     55

In [10]:
print(df.head())
print(df.tail())
print("shape",df.shape)
print("columns",df.columns.tolist())
print(df.dtypes)
print(df.info())
print(df.describe())

     Name  Age Department  Marks
0   Alice   25        CSE     90
1     Bob   28        ECE     80
2  Claire   30         IT     66
3    Lisa   26        CSE     74
4     Tom   14        ECE     55
     Name  Age Department  Marks
0   Alice   25        CSE     90
1     Bob   28        ECE     80
2  Claire   30         IT     66
3    Lisa   26        CSE     74
4     Tom   14        ECE     55
shape (5, 4)
columns ['Name', 'Age', 'Department', 'Marks']
Name          object
Age            int64
Department    object
Marks          int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None
             Age      Marks
count   5.000000   5.000000
mean   24.600000  73.000000
std     6.228965  13.341664
min    14.000000  55.000000
25%    25.000000  66.000000
50%    26.000000  74.000000
75%    28.000000  80.000000
max    30.000000  90.000000

In [5]:
iris_df=pd.read_csv("/content/iris.csv")
iris_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
print("Shape",iris_df.shape)
print("columns",iris_df.columns.tolist())
print("\n Data type:")
print(iris_df.dtypes)
print("\nMissing values:")
print(iris_df.isnull().sum())
print("\nInfomation")
iris_df.info()
print("\nSummary")
print(iris_df.describe(include="all"))

Shape (150, 5)
columns ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

 Data type:
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

Missing values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

Infomation
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

Summary
        sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.054000      3.758667     1.198667     NaN
std         0.828066     0.433594      1.764420     0.763161     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

Save and Load Excel

In [7]:
iris_df.to_excel("iris_output.xlsx",index=False)

In [9]:
iris_excel=pd.read_excel("iris_output.xlsx")
print(iris_excel.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Save and Load JSON

In [12]:
iris_df.to_json("iris_output.json",orient="records",indent=4)

In [13]:
iris_json=pd.read_json("iris_output.json")
print(iris_json.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [15]:
with open("iris_output.json","r") as file:
  json_data=file.read()
  print(json_data)

[
    {
        "sepal_length":5.1,
        "sepal_width":3.5,
        "petal_length":1.4,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.9,
        "sepal_width":3.0,
        "petal_length":1.4,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.7,
        "sepal_width":3.2,
        "petal_length":1.3,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.6,
        "sepal_width":3.1,
        "petal_length":1.5,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.0,
        "sepal_width":3.6,
        "petal_length":1.4,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.4,
        "sepal_width":3.9,
        "petal_length":1.7,
        "petal_width":0.4,
        "species":"setosa"
    },
    {
        "sepal_length":4.6,
        "sepal_width":3.4,
        "petal_length":1.4,
        "petal_width":0.3,
        "species":"setosa"
    },
    {
        "sepal_length":5.0,
        "sepal_width":3.4,
        "petal_length":1.5,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.4,
        "sepal_width":2.9,
        "petal_length":1.4,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.9,
        "sepal_width":3.1,
        "petal_length":1.5,
        "petal_width":0.1,
        "species":"setosa"
    },
    {
        "sepal_length":5.4,
        "sepal_width":3.7,
        "petal_length":1.5,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.8,
        "sepal_width":3.4,
        "petal_length":1.6,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.8,
        "sepal_width":3.0,
        "petal_length":1.4,
        "petal_width":0.1,
        "species":"setosa"
    },
    {
        "sepal_length":4.3,
        "sepal_width":3.0,
        "petal_length":1.1,
        "petal_width":0.1,
        "species":"setosa"
    },
    {
        "sepal_length":5.8,
        "sepal_width":4.0,
        "petal_length":1.2,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.7,
        "sepal_width":4.4,
        "petal_length":1.5,
        "petal_width":0.4,
        "species":"setosa"
    },
    {
        "sepal_length":5.4,
        "sepal_width":3.9,
        "petal_length":1.3,
        "petal_width":0.4,
        "species":"setosa"
    },
    {
        "sepal_length":5.1,
        "sepal_width":3.5,
        "petal_length":1.4,
        "petal_width":0.3,
        "species":"setosa"
    },
    {
        "sepal_length":5.7,
        "sepal_width":3.8,
        "petal_length":1.7,
        "petal_width":0.3,
        "species":"setosa"
    },
    {
        "sepal_length":5.1,
        "sepal_width":3.8,
        "petal_length":1.5,
        "petal_width":0.3,
        "species":"setosa"
    },
    {
        "sepal_length":5.4,
        "sepal_width":3.4,
        "petal_length":1.7,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.1,
        "sepal_width":3.7,
        "petal_length":1.5,
        "petal_width":0.4,
        "species":"setosa"
    },
    {
        "sepal_length":4.6,
        "sepal_width":3.6,
        "petal_length":1.0,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.1,
        "sepal_width":3.3,
        "petal_length":1.7,
        "petal_width":0.5,
        "species":"setosa"
    },
    {
        "sepal_length":4.8,
        "sepal_width":3.4,
        "petal_length":1.9,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.0,
        "sepal_width":3.0,
        "petal_length":1.6,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.0,
        "sepal_width":3.4,
        "petal_length":1.6,
        "petal_width":0.4,
        "species":"setosa"
    },
    {
        "sepal_length":5.2,
        "sepal_width":3.5,
        "petal_length":1.5,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.2,
        "sepal_width":3.4,
        "petal_length":1.4,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.7,
        "sepal_width":3.2,
        "petal_length":1.6,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.8,
        "sepal_width":3.1,
        "petal_length":1.6,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.4,
        "sepal_width":3.4,
        "petal_length":1.5,
        "petal_width":0.4,
        "species":"setosa"
    },
    {
        "sepal_length":5.2,
        "sepal_width":4.1,
        "petal_length":1.5,
        "petal_width":0.1,
        "species":"setosa"
    },
    {
        "sepal_length":5.5,
        "sepal_width":4.2,
        "petal_length":1.4,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.9,
        "sepal_width":3.1,
        "petal_length":1.5,
        "petal_width":0.1,
        "species":"setosa"
    },
    {
        "sepal_length":5.0,
        "sepal_width":3.2,
        "petal_length":1.2,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.5,
        "sepal_width":3.5,
        "petal_length":1.3,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.9,
        "sepal_width":3.1,
        "petal_length":1.5,
        "petal_width":0.1,
        "species":"setosa"
    },
    {
        "sepal_length":4.4,
        "sepal_width":3.0,
        "petal_length":1.3,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.1,
        "sepal_width":3.4,
        "petal_length":1.5,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.0,
        "sepal_width":3.5,
        "petal_length":1.3,
        "petal_width":0.3,
        "species":"setosa"
    },
    {
        "sepal_length":4.5,
        "sepal_width":2.3,
        "petal_length":1.3,
        "petal_width":0.3,
        "species":"setosa"
    },
    {
        "sepal_length":4.4,
        "sepal_width":3.2,
        "petal_length":1.3,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.0,
        "sepal_width":3.5,
        "petal_length":1.6,
        "petal_width":0.6,
        "species":"setosa"
    },
    {
        "sepal_length":5.1,
        "sepal_width":3.8,
        "petal_length":1.9,
        "petal_width":0.4,
        "species":"setosa"
    },
    {
        "sepal_length":4.8,
        "sepal_width":3.0,
        "petal_length":1.4,
        "petal_width":0.3,
        "species":"setosa"
    },
    {
        "sepal_length":5.1,
        "sepal_width":3.8,
        "petal_length":1.6,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":4.6,
        "sepal_width":3.2,
        "petal_length":1.4,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.3,
        "sepal_width":3.7,
        "petal_length":1.5,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":5.0,
        "sepal_width":3.3,
        "petal_length":1.4,
        "petal_width":0.2,
        "species":"setosa"
    },
    {
        "sepal_length":7.0,
        "sepal_width":3.2,
        "petal_length":4.7,
        "petal_width":1.4,
        "species":"versicolor"
    },
    {
        "sepal_length":6.4,
        "sepal_width":3.2,
        "petal_length":4.5,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":6.9,
        "sepal_width":3.1,
        "petal_length":4.9,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":5.5,
        "sepal_width":2.3,
        "petal_length":4.0,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":6.5,
        "sepal_width":2.8,
        "petal_length":4.6,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":5.7,
        "sepal_width":2.8,
        "petal_length":4.5,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":6.3,
        "sepal_width":3.3,
        "petal_length":4.7,
        "petal_width":1.6,
        "species":"versicolor"
    },
    {
        "sepal_length":4.9,
        "sepal_width":2.4,
        "petal_length":3.3,
        "petal_width":1.0,
        "species":"versicolor"
    },
    {
        "sepal_length":6.6,
        "sepal_width":2.9,
        "petal_length":4.6,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":5.2,
        "sepal_width":2.7,
        "petal_length":3.9,
        "petal_width":1.4,
        "species":"versicolor"
    },
    {
        "sepal_length":5.0,
        "sepal_width":2.0,
        "petal_length":3.5,
        "petal_width":1.0,
        "species":"versicolor"
    },
    {
        "sepal_length":5.9,
        "sepal_width":3.0,
        "petal_length":4.2,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":6.0,
        "sepal_width":2.2,
        "petal_length":4.0,
        "petal_width":1.0,
        "species":"versicolor"
    },
    {
        "sepal_length":6.1,
        "sepal_width":2.9,
        "petal_length":4.7,
        "petal_width":1.4,
        "species":"versicolor"
    },
    {
        "sepal_length":5.6,
        "sepal_width":2.9,
        "petal_length":3.6,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":6.7,
        "sepal_width":3.1,
        "petal_length":4.4,
        "petal_width":1.4,
        "species":"versicolor"
    },
    {
        "sepal_length":5.6,
        "sepal_width":3.0,
        "petal_length":4.5,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":5.8,
        "sepal_width":2.7,
        "petal_length":4.1,
        "petal_width":1.0,
        "species":"versicolor"
    },
    {
        "sepal_length":6.2,
        "sepal_width":2.2,
        "petal_length":4.5,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":5.6,
        "sepal_width":2.5,
        "petal_length":3.9,
        "petal_width":1.1,
        "species":"versicolor"
    },
    {
        "sepal_length":5.9,
        "sepal_width":3.2,
        "petal_length":4.8,
        "petal_width":1.8,
        "species":"versicolor"
    },
    {
        "sepal_length":6.1,
        "sepal_width":2.8,
        "petal_length":4.0,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":6.3,
        "sepal_width":2.5,
        "petal_length":4.9,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":6.1,
        "sepal_width":2.8,
        "petal_length":4.7,
        "petal_width":1.2,
        "species":"versicolor"
    },
    {
        "sepal_length":6.4,
        "sepal_width":2.9,
        "petal_length":4.3,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":6.6,
        "sepal_width":3.0,
        "petal_length":4.4,
        "petal_width":1.4,
        "species":"versicolor"
    },
    {
        "sepal_length":6.8,
        "sepal_width":2.8,
        "petal_length":4.8,
        "petal_width":1.4,
        "species":"versicolor"
    },
    {
        "sepal_length":6.7,
        "sepal_width":3.0,
        "petal_length":5.0,
        "petal_width":1.7,
        "species":"versicolor"
    },
    {
        "sepal_length":6.0,
        "sepal_width":2.9,
        "petal_length":4.5,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":5.7,
        "sepal_width":2.6,
        "petal_length":3.5,
        "petal_width":1.0,
        "species":"versicolor"
    },
    {
        "sepal_length":5.5,
        "sepal_width":2.4,
        "petal_length":3.8,
        "petal_width":1.1,
        "species":"versicolor"
    },
    {
        "sepal_length":5.5,
        "sepal_width":2.4,
        "petal_length":3.7,
        "petal_width":1.0,
        "species":"versicolor"
    },
    {
        "sepal_length":5.8,
        "sepal_width":2.7,
        "petal_length":3.9,
        "petal_width":1.2,
        "species":"versicolor"
    },
    {
        "sepal_length":6.0,
        "sepal_width":2.7,
        "petal_length":5.1,
        "petal_width":1.6,
        "species":"versicolor"
    },
    {
        "sepal_length":5.4,
        "sepal_width":3.0,
        "petal_length":4.5,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":6.0,
        "sepal_width":3.4,
        "petal_length":4.5,
        "petal_width":1.6,
        "species":"versicolor"
    },
    {
        "sepal_length":6.7,
        "sepal_width":3.1,
        "petal_length":4.7,
        "petal_width":1.5,
        "species":"versicolor"
    },
    {
        "sepal_length":6.3,
        "sepal_width":2.3,
        "petal_length":4.4,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":5.6,
        "sepal_width":3.0,
        "petal_length":4.1,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":5.5,
        "sepal_width":2.5,
        "petal_length":4.0,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":5.5,
        "sepal_width":2.6,
        "petal_length":4.4,
        "petal_width":1.2,
        "species":"versicolor"
    },
    {
        "sepal_length":6.1,
        "sepal_width":3.0,
        "petal_length":4.6,
        "petal_width":1.4,
        "species":"versicolor"
    },
    {
        "sepal_length":5.8,
        "sepal_width":2.6,
        "petal_length":4.0,
        "petal_width":1.2,
        "species":"versicolor"
    },
    {
        "sepal_length":5.0,
        "sepal_width":2.3,
        "petal_length":3.3,
        "petal_width":1.0,
        "species":"versicolor"
    },
    {
        "sepal_length":5.6,
        "sepal_width":2.7,
        "petal_length":4.2,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":5.7,
        "sepal_width":3.0,
        "petal_length":4.2,
        "petal_width":1.2,
        "species":"versicolor"
    },
    {
        "sepal_length":5.7,
        "sepal_width":2.9,
        "petal_length":4.2,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":6.2,
        "sepal_width":2.9,
        "petal_length":4.3,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":5.1,
        "sepal_width":2.5,
        "petal_length":3.0,
        "petal_width":1.1,
        "species":"versicolor"
    },
    {
        "sepal_length":5.7,
        "sepal_width":2.8,
        "petal_length":4.1,
        "petal_width":1.3,
        "species":"versicolor"
    },
    {
        "sepal_length":6.3,
        "sepal_width":3.3,
        "petal_length":6.0,
        "petal_width":2.5,
        "species":"virginica"
    },
    {
        "sepal_length":5.8,
        "sepal_width":2.7,
        "petal_length":5.1,
        "petal_width":1.9,
        "species":"virginica"
    },
    {
        "sepal_length":7.1,
        "sepal_width":3.0,
        "petal_length":5.9,
        "petal_width":2.1,
        "species":"virginica"
    },
    {
        "sepal_length":6.3,
        "sepal_width":2.9,
        "petal_length":5.6,
        "petal_width":1.8,
        "species":"virginica"
    },
    {
        "sepal_length":6.5,
        "sepal_width":3.0,
        "petal_length":5.8,
        "petal_width":2.2,
        "species":"virginica"
    },
    {
        "sepal_length":7.6,
        "sepal_width":3.0,
        "petal_length":6.6,
        "petal_width":2.1,
        "species":"virginica"
    },
    {
        "sepal_length":4.9,
        "sepal_width":2.5,
        "petal_length":4.5,
        "petal_width":1.7,
        "species":"virginica"
    },
    {
        "sepal_length":7.3,
        "sepal_width":2.9,
        "petal_length":6.3,
        "petal_width":1.8,
        "species":"virginica"
    },
    {
        "sepal_length":6.7,
        "sepal_width":2.5,
        "petal_length":5.8,
        "petal_width":1.8,
        "species":"virginica"
    },
    {
        "sepal_length":7.2,
        "sepal_width":3.6,
        "petal_length":6.1,
        "petal_width":2.5,
        "species":"virginica"
    },
    {
        "sepal_length":6.5,
        "sepal_width":3.2,
        "petal_length":5.1,
        "petal_width":2.0,
        "species":"virginica"
    },
    {
        "sepal_length":6.4,
        "sepal_width":2.7,
        "petal_length":5.3,
        "petal_width":1.9,
        "species":"virginica"
    },
    {
        "sepal_length":6.8,
        "sepal_width":3.0,
        "petal_length":5.5,
        "petal_width":2.1,
        "species":"virginica"
    },
    {
        "sepal_length":5.7,
        "sepal_width":2.5,
        "petal_length":5.0,
        "petal_width":2.0,
        "species":"virginica"
    },
    {
        "sepal_length":5.8,
        "sepal_width":2.8,
        "petal_length":5.1,
        "petal_width":2.4,
        "species":"virginica"
    },
    {
        "sepal_length":6.4,
        "sepal_width":3.2,
        "petal_length":5.3,
        "petal_width":2.3,
        "species":"virginica"
    },
    {
        "sepal_length":6.5,
        "sepal_width":3.0,
        "petal_length":5.5,
        "petal_width":1.8,
        "species":"virginica"
    },
    {
        "sepal_length":7.7,
        "sepal_width":3.8,
        "petal_length":6.7,
        "petal_width":2.2,
        "species":"virginica"
    },
    {
        "sepal_length":7.7,
        "sepal_width":2.6,
        "petal_length":6.9,
        "petal_width":2.3,
        "species":"virginica"
    },
    {
        "sepal_length":6.0,
        "sepal_width":2.2,
        "petal_length":5.0,
        "petal_width":1.5,
        "species":"virginica"
    },
    {
        "sepal_length":6.9,
        "sepal_width":3.2,
        "petal_length":5.7,
        "petal_width":2.3,
        "species":"virginica"
    },
    {
        "sepal_length":5.6,
        "sepal_width":2.8,
        "petal_length":4.9,
        "petal_width":2.0,
        "species":"virginica"
    },
    {
        "sepal_length":7.7,
        "sepal_width":2.8,
        "petal_length":6.7,
        "petal_width":2.0,
        "species":"virginica"
    },
    {
        "sepal_length":6.3,
        "sepal_width":2.7,
        "petal_length":4.9,
        "petal_width":1.8,
        "species":"virginica"
    },
    {
        "sepal_length":6.7,
        "sepal_width":3.3,
        "petal_length":5.7,
        "petal_width":2.1,
        "species":"virginica"
    },
    {
        "sepal_length":7.2,
        "sepal_width":3.2,
        "petal_length":6.0,
        "petal_width":1.8,
        "species":"virginica"
    },
    {
        "sepal_length":6.2,
        "sepal_width":2.8,
        "petal_length":4.8,
        "petal_width":1.8,
        "species":"virginica"
    },
    {
        "sepal_length":6.1,
        "sepal_width":3.0,
        "petal_length":4.9,
        "petal_width":1.8,
        "species":"virginica"
    },
    {
        "sepal_length":6.4,
        "sepal_width":2.8,
        "petal_length":5.6,
        "petal_width":2.1,
        "species":"virginica"
    },
    {
        "sepal_length":7.2,
        "sepal_width":3.0,
        "petal_length":5.8,
        "petal_width":1.6,
        "species":"virginica"
    },
    {
        "sepal_length":7.4,
        "sepal_width":2.8,
        "petal_length":6.1,
        "petal_width":1.9,
        "species":"virginica"
    },
    {
        "sepal_length":7.9,

Sava and Load Parquet

In [16]:
iris_df.to_parquet("iris_output.parquet",index=False)

In [17]:
iris_parquet=pd.read_parquet("iris_output.parquet")
print(iris_parquet.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

#Created/downloaded a data
# downloded from kaggle
#load the data
#pandas dataframe
#insepected a data
#store the data in different format
  ##csv
    =>read_csv()
    =>to_csv()
  ##exel
    =>read_excel()
    =>to_excel()
  ##json
    =>read_json()
    =>to_json()
  ##parquet
    =>read_parquet()
    =>to_parquet()

Compare file sizes

['.config', 'iris_output.xlsx', '.ipynb_checkpoints', 'iris.csv', 'iris_output.json', 'iris_output.parquet', 'sample_data']

In [26]:
import os
files=["iris.csv","iris_output.xlsx","iris_output.json","iris_output.parquet"]
for file in files:
  size=os.path.getsize(file)
  print(f"{file} : {size} bytes")

iris.csv : 3858 bytes
iris_output.xlsx : 8424 bytes
iris_output.json : 22852 bytes
iris_output.parquet : 4575 bytes

Loading only selected colums

In [27]:
iris_sel=pd.read_csv("iris.csv",usecols=["sepal_length","sepal_width"])
print(iris_sel.head())

   sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6

Loading a limited number of rows

In [29]:
sample=pd.read_csv("iris.csv",nrows=10)
sample

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

Filtering data

In [30]:
result=iris_df[iris_df["sepal_length"]>6]
result.head()

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
54           6.5          2.8           4.6          1.5  versicolor
56           6.3          3.3           4.7          1.6  versicolor